version: '2'
services:
  dspace:
    image: testds
    ports:
     - "8081:8080"
    # - "8084:8443"
    # - "3000:443"
    volumes:
     - testhome:/opt/dspace
     - testsrc:/home/dspace
    environment:
     - PGPASSWORD=postgres
    restart: always
    mem_limit: 3g
  postgres:
    image: postgresdspace
    volumes:
      - /docker/postgrestest:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    mem_limit: 512m
volumes:
  testhome:
  testsrc:
